version: "3.8"
services:
  # Proxy
  traefik:
    container_name: traefik
    image: traefik:latest
    restart: always
    ports:
      - 443:443
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=mediacenter_net"

      # Main domain
      - "traefik.http.routers.traefik.rule=Host(`$TRAEFIK_DOMAIN.$ADMIN_DOMAIN.$DOMAIN`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=mytlschallenge"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.service=api@internal"

      # Watchtower automated update label
      - "com.centurylinklabs.watchtower.enable=true"
    command:
      - "--log.level=INFO"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=$CLOUDFLARE_EMAIL"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    volumes:
      - $APPDATA/traefik:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - media_net

  # Ldap
  openldap:
    container_name: ldap
    image: osixia/openldap:1.4.0
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    hostname: $DOMAIN
    ports:
      - 389:389
      - 636:636
    environment:
      LDAP_ORGANISATION: $LDAP_ORGANISATION_NAME
      LDAP_DOMAIN: $DOMAIN
      LDAP_ADMIN_PASSWORD: $LDAP_ADMIN_PASSWORD
      LDAP_CONFIG_PASSWORD: $LDAP_CONFIG_PASSWORD
      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_USERNAME: "bind"
      LDAP_READONLY_USER_PASSWORD: $LDAP_READONLY_USER_PASSWORD
      LDAP_RFC2307BIS_SCHEMA: "false"
    volumes:
      - $APPDATA/openldap/config:/etc/ldap/slapd.d
      - $APPDATA/openldap/data:/var/lib/ldap
    networks:
      - media_net

  # Databases
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
    volumes:
      - $PWD/config/mariadb/plugins.cnf:/etc/mysql/mariadb.conf.d/plugins.cnf
      - $APPDATA/mariadb:/var/lib/mysql
    networks:
      - db_net

  # Utilities
  phpldapadmin:
    container_name: ldap-admin
    image: osixia/phpldapadmin:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=mediacenter_net"

      # Main domain
      - "traefik.http.routers.phpldapadmin.rule=Host(`$PHP_LDAP_ADMIN.$ADMIN_DOMAIN.$DOMAIN`)"
      - "traefik.http.routers.phpldapadmin.entrypoints=websecure"
      - "traefik.http.routers.phpldapadmin.tls.certresolver=mytlschallenge"
      - "traefik.http.services.phpldapadmin.loadbalancer.server.port=80"
      - "traefik.http.routers.phpldapadmin.service=phpldapadmin"

      # Watchtower automated update label
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      # PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'openldap': [{'login': [{'attr': 'cn'}]}]}]"
      PHPLDAPADMIN_HTTPS: "false"
      PHPLDAPADMIN_TRUST_PROXY_SSL: "true"
    networks:
      - media_net

  phpmyadmin:
    container_name: mariadb-admin
    image: phpmyadmin
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=mediacenter_net"

      # Main domain
      - "traefik.http.routers.phpmyadmin.rule=Host(`$PHP_MY_ADMIN_DOMAIN.$ADMIN_DOMAIN.$DOMAIN`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=mytlschallenge"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
      - "traefik.http.routers.phpmyadmin.service=phpmyadmin"

      # Watchtower automated update label
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      PMA_HOST: mariadb
    networks:
      - media_net
      - db_net

  cloudflare-companion:
    image: tiredofit/traefik-cloudflare-companion
    container_name: cloudflare
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      CF_EMAIL: $CLOUDFLARE_EMAIL
      CF_TOKEN: $CLOUDFLARE_API_TOKEN
      TARGET_DOMAIN: $DOMAIN
      DOMAIN1: $DOMAIN
      DOMAIN1_ZONE_ID: $CLOUDFLARE_DOMAIN_ZONE_ID
      DOMAIN1_PROXIED: "false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - media_net

  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    command:
      - --label-enable
      - --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - media_net

networks:
  db_net:
    name: database_net
  media_net:
    name: mediacenter_net
